### ISSUE TITLE
threadscope fails to build with ghc 8.2.2

### ISSUE THREAD

**Issue by nek0** [haskell/ThreadScope#85]
Hi there,

when trying to build ThreadScope, compilation fails with this error:
```
GUI/BookmarkView.hs:84:39: error:
    • Couldn't match expected type ‘Maybe model0’
                  with actual type ‘ListStore (Timestamp, String)’
    • In the second argument of ‘treeViewSetModel’, namely
        ‘bookmarkStore’
      In a stmt of a 'do' block:
        treeViewSetModel bookmarkTreeView bookmarkStore
      In the expression:
        do let getWidget cast name = builderGetObject builder cast name
           bookmarkTreeView <- getWidget castToTreeView "bookmark_list"
           bookmarkStore <- listStoreNew []
           columnTs <- treeViewColumnNew
           ....
   |
84 |     treeViewSetModel bookmarkTreeView bookmarkStore
   |                                       ^^^^^^^^^^^^^
```

Is this some error on my side or really an issue?

Thanks for your time.

**Comment by maoe** [comment]
This is caused by [a breaking change](https://github.com/gtk2hs/gtk2hs/pull/239) in gtk. In theory [gtk-0.14.9 should have bumped the second version component](https://github.com/gtk2hs/gtk2hs/issues/247).

There's a fix for threadscope in #84 but I haven't gotten around to fixing the build issue on AppVeyor properly. I hope I can take a look in this week.

**Comment by maoe** [comment]
@nek0 I merged #84 yesterday. Can you check if master builds fine in your environment?

**Comment by maoe** [comment]
Great! Thanks for confirming.
