### ISSUE TITLE
can't install threadscope on ghc 8.2.1 rc3

### ISSUE THREAD

**Issue by GeorgeCo** [haskell/ThreadScope#63]
can't install threadscope on ghc 8.2.1 rc3
 cabal install -j5 threadscope
cabal install -j5 threadscope
Resolving dependencies...
Configuring threadscope-0.2.7...
Building threadscope-0.2.7...
Failed to install threadscope-0.2.7
Build log ( /Users/gcolpitts/.cabal/logs/threadscope-0.2.7.log ):
cabal: Entering directory '/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-21811/threadscope-0.2.7'
Configuring threadscope-0.2.7...
Building threadscope-0.2.7...
Preprocessing executable 'threadscope' for threadscope-0.2.7...
[ 1 of 35] Compiling Events.EventDuration ( Events/EventDuration.hs, dist/build/threadscope/threadscope-tmp/Events/EventDuration.o )
...
Events/HECs.hs:62:17: error:
    • The constructor ‘Event’ should have 3 arguments, but has been given 2
    • In the pattern: Event ts (UserMarker mark)
      In the pattern: CapEvent _ (Event ts (UserMarker mark))
      In a stmt of a list comprehension:
        CapEvent _ (Event ts (UserMarker mark)) <- elems
                                                     (hecEventArray hecs)
   |
62 |   | CapEvent _ (Event ts (UserMarker mark)) <- elems (hecEventArray hecs) ]
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-21811/threadscope-0.2.7'
cabal: Error: some packages failed to install:
threadscope-0.2.7 failed during the building phase. The exception was:
ExitFailure 1

**Comment by maoe** [comment]
Current version on Hackage doesn't build with the latest ghc-events.

@Mikolaj or someone: could you please upload a new version to Hackage? Current master builds fine with the latest ghc-events.

**Comment by Mikolaj** [comment]
Oh, yes, the releases were always coordinated. If @simonmar doesn't object, I'd just give you hackage upload rights.

**Comment by simonmar** [comment]
I don't object!

**Comment by Mikolaj** [comment]
Done. :) 

@maoe: if you'd like me to test first, please let me know, but I don't have ghc 8.2.1 rc3 handy, so I'd just compile on 8.0.2 and display a few eventlogs.

**Comment by maoe** [comment]
Thanks!

> if you'd like me to test first, please let me know, but I don't have ghc 8.2.1 rc3 handy, so I'd just compile on 8.0.2 and display a few eventlogs.

Yes, please do.

In the meanwhile, I'll make a PR for enabling Travis CI.

**Comment by maoe** [comment]
Also we probably should revise the existing packages with a upper version bound on ghc-events.

**Comment by Mikolaj** [comment]
Eventually, I tested TS with GHC 8.0.1. It compiles and works fine with github's ghc-events.

**Comment by maoe** [comment]
@Mikolaj Thanks for testing! I'm now experimenting the macOS support on Travis CI. Also I'm going to add AppVeryor build for Windows.

**Comment by maoe** [comment]
I've tightened upper version bound for ghc-events for a couple of existing releases of threadscope.

@GeorgeCo could you try again?

Also we'll be enabling Travis/AppVeyor in #64 and I'm going to tighten some upper version bounds to minimize this kind of failures.

**Comment by GeorgeCo** [comment]
Yes, it installs now.
Thanks!

**Comment by maoe** [comment]
Thanks for checking. Closing.
